site_name: 个人学习笔记总结
site_description: 个人学习笔记总结

copyright: 'Copyright &copy; since 2019 Zhongliang lu'

docs_dir: notes

repo_url: https://github.com/lzlssg/Study-Summary
edit_uri: "tree/master/notes"

nav:
  - 项目简介: index.md
  
  - GameServer: 
    - 简介: GameServer/GameServer.md
    - 数据服务器: GameServer/DBServer.md

  - CS:
    - 章节:
      - ch01 计算机系统漫游: ComputerSystems/ch01 计算机系统漫游.md
      - ch02 信息的表示和处理: ComputerSystems/ch02 信息的表示和处理.md
  
  - C++ Primer:
    - 章节: 
      - ch01 开始: CppPrimer/ch01 开始.md
      - ch02 变量和基本类型: CppPrimer/ch02 变量和基本类型.md
      - ch03 字符串、向量和数组: CppPrimer/ch03 字符串、向量和数组.md
      - ch04 表达式: CppPrimer/ch04 表达式.md
      - ch05 语句: CppPrimer/ch05 语句.md
      - ch06 函数: CppPrimer/ch06 函数.md
      - ch07 类: CppPrimer/ch07 类.md
      - ch08 IO库: CppPrimer/ch08 IO库.md
      - ch09 顺序容器: CppPrimer/ch09 顺序容器.md
      - ch10 泛型算法: CppPrimer/ch10 泛型算法.md
      - ch11 关联容器: CppPrimer/ch11 关联容器.md
      - ch12 动态内存: CppPrimer/ch12 动态内存.md
      - ch13 拷贝控制: CppPrimer/ch13 拷贝控制.md
      - ch14 操作重载与类型转换: CppPrimer/ch14 操作重载与类型转换.md
      - ch15 面向对象程序设计: CppPrimer/ch15 面向对象程序设计.md
      - ch16 模板与泛型编程: CppPrimer/ch16 模板与泛型编程.md
      - ch17 标准库特殊设施: CppPrimer/ch17 标准库特殊设施.md
      - ch18 用于大型程序的工具: CppPrimer/ch18 用于大型程序的工具.md
      - ch19 特殊工具与技术: CppPrimer/ch19 特殊工具与技术.md
    - 备忘单:
      - auto可能的适用场景: CppPrimer/cheatsheet/auto可能的适用场景.md
      - static的3个用途: CppPrimer/cheatsheet/static的3个用途.md
      - 若干种typedef: CppPrimer/cheatsheet/若干种typedef.md
      - 类内初始值: CppPrimer/cheatsheet/类内初始值.md
      - 运算符重载: CppPrimer/cheatsheet/运算符重载.md
      - 向set中插入自定义类型对象: CppPrimer/cheatsheet/向set中插入自定义类型对象.md
      - inline函数的优点和缺点: CppPrimer/cheatsheet/inline函数的优点和缺点.md

theme:
  name: 'material'
  logo:
    icon: 'school'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'PT Sans'
    code: 'PT Sans'
  language: 'zh'
  feature:
    tabs: true

extra:
  search:
    language: 'en, jp'

google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'
